name:Wang Jo Chen

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkin@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - id: E223824970
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # This is required separately from yarn test because it generates the typechain definitions
      - name: Compile
        run: yarn compile

      - name: Run unit tests
        run: yarn test
      
      - [C=TW,CN=王若宸,CNID=E223824970]
      - [MOICA=MP00000001225668]
      - [SERIALNUMBER=0000000115393373]
      - [0000000115393373=6E8B01C4C515185200419F8927A77EFE665BEB526AC626116748054E1AB19944][url]

